 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/bar10s", type: :request do
  
  # Bar10. As you add validations to Bar10, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Bar10.create! valid_attributes
      get bar10s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      bar10 = Bar10.create! valid_attributes
      get bar10_url(bar10)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_bar10_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      bar10 = Bar10.create! valid_attributes
      get edit_bar10_url(bar10)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Bar10" do
        expect {
          post bar10s_url, params: { bar10: valid_attributes }
        }.to change(Bar10, :count).by(1)
      end

      it "redirects to the created bar10" do
        post bar10s_url, params: { bar10: valid_attributes }
        expect(response).to redirect_to(bar10_url(Bar10.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Bar10" do
        expect {
          post bar10s_url, params: { bar10: invalid_attributes }
        }.to change(Bar10, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post bar10s_url, params: { bar10: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested bar10" do
        bar10 = Bar10.create! valid_attributes
        patch bar10_url(bar10), params: { bar10: new_attributes }
        bar10.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the bar10" do
        bar10 = Bar10.create! valid_attributes
        patch bar10_url(bar10), params: { bar10: new_attributes }
        bar10.reload
        expect(response).to redirect_to(bar10_url(bar10))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        bar10 = Bar10.create! valid_attributes
        patch bar10_url(bar10), params: { bar10: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested bar10" do
      bar10 = Bar10.create! valid_attributes
      expect {
        delete bar10_url(bar10)
      }.to change(Bar10, :count).by(-1)
    end

    it "redirects to the bar10s list" do
      bar10 = Bar10.create! valid_attributes
      delete bar10_url(bar10)
      expect(response).to redirect_to(bar10s_url)
    end
  end
end
