 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/bar18s", type: :request do
  
  # Bar18. As you add validations to Bar18, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Bar18.create! valid_attributes
      get bar18s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      bar18 = Bar18.create! valid_attributes
      get bar18_url(bar18)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_bar18_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      bar18 = Bar18.create! valid_attributes
      get edit_bar18_url(bar18)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Bar18" do
        expect {
          post bar18s_url, params: { bar18: valid_attributes }
        }.to change(Bar18, :count).by(1)
      end

      it "redirects to the created bar18" do
        post bar18s_url, params: { bar18: valid_attributes }
        expect(response).to redirect_to(bar18_url(Bar18.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Bar18" do
        expect {
          post bar18s_url, params: { bar18: invalid_attributes }
        }.to change(Bar18, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post bar18s_url, params: { bar18: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested bar18" do
        bar18 = Bar18.create! valid_attributes
        patch bar18_url(bar18), params: { bar18: new_attributes }
        bar18.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the bar18" do
        bar18 = Bar18.create! valid_attributes
        patch bar18_url(bar18), params: { bar18: new_attributes }
        bar18.reload
        expect(response).to redirect_to(bar18_url(bar18))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        bar18 = Bar18.create! valid_attributes
        patch bar18_url(bar18), params: { bar18: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested bar18" do
      bar18 = Bar18.create! valid_attributes
      expect {
        delete bar18_url(bar18)
      }.to change(Bar18, :count).by(-1)
    end

    it "redirects to the bar18s list" do
      bar18 = Bar18.create! valid_attributes
      delete bar18_url(bar18)
      expect(response).to redirect_to(bar18s_url)
    end
  end
end
