 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/bar13s", type: :request do
  
  # Bar13. As you add validations to Bar13, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Bar13.create! valid_attributes
      get bar13s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      bar13 = Bar13.create! valid_attributes
      get bar13_url(bar13)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_bar13_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      bar13 = Bar13.create! valid_attributes
      get edit_bar13_url(bar13)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Bar13" do
        expect {
          post bar13s_url, params: { bar13: valid_attributes }
        }.to change(Bar13, :count).by(1)
      end

      it "redirects to the created bar13" do
        post bar13s_url, params: { bar13: valid_attributes }
        expect(response).to redirect_to(bar13_url(Bar13.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Bar13" do
        expect {
          post bar13s_url, params: { bar13: invalid_attributes }
        }.to change(Bar13, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post bar13s_url, params: { bar13: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested bar13" do
        bar13 = Bar13.create! valid_attributes
        patch bar13_url(bar13), params: { bar13: new_attributes }
        bar13.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the bar13" do
        bar13 = Bar13.create! valid_attributes
        patch bar13_url(bar13), params: { bar13: new_attributes }
        bar13.reload
        expect(response).to redirect_to(bar13_url(bar13))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        bar13 = Bar13.create! valid_attributes
        patch bar13_url(bar13), params: { bar13: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested bar13" do
      bar13 = Bar13.create! valid_attributes
      expect {
        delete bar13_url(bar13)
      }.to change(Bar13, :count).by(-1)
    end

    it "redirects to the bar13s list" do
      bar13 = Bar13.create! valid_attributes
      delete bar13_url(bar13)
      expect(response).to redirect_to(bar13s_url)
    end
  end
end
