 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/bar16s", type: :request do
  
  # Bar16. As you add validations to Bar16, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Bar16.create! valid_attributes
      get bar16s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      bar16 = Bar16.create! valid_attributes
      get bar16_url(bar16)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_bar16_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      bar16 = Bar16.create! valid_attributes
      get edit_bar16_url(bar16)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Bar16" do
        expect {
          post bar16s_url, params: { bar16: valid_attributes }
        }.to change(Bar16, :count).by(1)
      end

      it "redirects to the created bar16" do
        post bar16s_url, params: { bar16: valid_attributes }
        expect(response).to redirect_to(bar16_url(Bar16.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Bar16" do
        expect {
          post bar16s_url, params: { bar16: invalid_attributes }
        }.to change(Bar16, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post bar16s_url, params: { bar16: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested bar16" do
        bar16 = Bar16.create! valid_attributes
        patch bar16_url(bar16), params: { bar16: new_attributes }
        bar16.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the bar16" do
        bar16 = Bar16.create! valid_attributes
        patch bar16_url(bar16), params: { bar16: new_attributes }
        bar16.reload
        expect(response).to redirect_to(bar16_url(bar16))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        bar16 = Bar16.create! valid_attributes
        patch bar16_url(bar16), params: { bar16: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested bar16" do
      bar16 = Bar16.create! valid_attributes
      expect {
        delete bar16_url(bar16)
      }.to change(Bar16, :count).by(-1)
    end

    it "redirects to the bar16s list" do
      bar16 = Bar16.create! valid_attributes
      delete bar16_url(bar16)
      expect(response).to redirect_to(bar16s_url)
    end
  end
end
