 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/bar24s", type: :request do
  
  # Bar24. As you add validations to Bar24, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Bar24.create! valid_attributes
      get bar24s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      bar24 = Bar24.create! valid_attributes
      get bar24_url(bar24)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_bar24_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      bar24 = Bar24.create! valid_attributes
      get edit_bar24_url(bar24)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Bar24" do
        expect {
          post bar24s_url, params: { bar24: valid_attributes }
        }.to change(Bar24, :count).by(1)
      end

      it "redirects to the created bar24" do
        post bar24s_url, params: { bar24: valid_attributes }
        expect(response).to redirect_to(bar24_url(Bar24.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Bar24" do
        expect {
          post bar24s_url, params: { bar24: invalid_attributes }
        }.to change(Bar24, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post bar24s_url, params: { bar24: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested bar24" do
        bar24 = Bar24.create! valid_attributes
        patch bar24_url(bar24), params: { bar24: new_attributes }
        bar24.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the bar24" do
        bar24 = Bar24.create! valid_attributes
        patch bar24_url(bar24), params: { bar24: new_attributes }
        bar24.reload
        expect(response).to redirect_to(bar24_url(bar24))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        bar24 = Bar24.create! valid_attributes
        patch bar24_url(bar24), params: { bar24: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested bar24" do
      bar24 = Bar24.create! valid_attributes
      expect {
        delete bar24_url(bar24)
      }.to change(Bar24, :count).by(-1)
    end

    it "redirects to the bar24s list" do
      bar24 = Bar24.create! valid_attributes
      delete bar24_url(bar24)
      expect(response).to redirect_to(bar24s_url)
    end
  end
end
