 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/bar31s", type: :request do
  
  # Bar31. As you add validations to Bar31, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Bar31.create! valid_attributes
      get bar31s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      bar31 = Bar31.create! valid_attributes
      get bar31_url(bar31)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_bar31_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      bar31 = Bar31.create! valid_attributes
      get edit_bar31_url(bar31)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Bar31" do
        expect {
          post bar31s_url, params: { bar31: valid_attributes }
        }.to change(Bar31, :count).by(1)
      end

      it "redirects to the created bar31" do
        post bar31s_url, params: { bar31: valid_attributes }
        expect(response).to redirect_to(bar31_url(Bar31.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Bar31" do
        expect {
          post bar31s_url, params: { bar31: invalid_attributes }
        }.to change(Bar31, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post bar31s_url, params: { bar31: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested bar31" do
        bar31 = Bar31.create! valid_attributes
        patch bar31_url(bar31), params: { bar31: new_attributes }
        bar31.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the bar31" do
        bar31 = Bar31.create! valid_attributes
        patch bar31_url(bar31), params: { bar31: new_attributes }
        bar31.reload
        expect(response).to redirect_to(bar31_url(bar31))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        bar31 = Bar31.create! valid_attributes
        patch bar31_url(bar31), params: { bar31: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested bar31" do
      bar31 = Bar31.create! valid_attributes
      expect {
        delete bar31_url(bar31)
      }.to change(Bar31, :count).by(-1)
    end

    it "redirects to the bar31s list" do
      bar31 = Bar31.create! valid_attributes
      delete bar31_url(bar31)
      expect(response).to redirect_to(bar31s_url)
    end
  end
end
