 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/bar3s", type: :request do
  
  # Bar3. As you add validations to Bar3, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Bar3.create! valid_attributes
      get bar3s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      bar3 = Bar3.create! valid_attributes
      get bar3_url(bar3)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_bar3_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      bar3 = Bar3.create! valid_attributes
      get edit_bar3_url(bar3)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Bar3" do
        expect {
          post bar3s_url, params: { bar3: valid_attributes }
        }.to change(Bar3, :count).by(1)
      end

      it "redirects to the created bar3" do
        post bar3s_url, params: { bar3: valid_attributes }
        expect(response).to redirect_to(bar3_url(Bar3.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Bar3" do
        expect {
          post bar3s_url, params: { bar3: invalid_attributes }
        }.to change(Bar3, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post bar3s_url, params: { bar3: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested bar3" do
        bar3 = Bar3.create! valid_attributes
        patch bar3_url(bar3), params: { bar3: new_attributes }
        bar3.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the bar3" do
        bar3 = Bar3.create! valid_attributes
        patch bar3_url(bar3), params: { bar3: new_attributes }
        bar3.reload
        expect(response).to redirect_to(bar3_url(bar3))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        bar3 = Bar3.create! valid_attributes
        patch bar3_url(bar3), params: { bar3: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested bar3" do
      bar3 = Bar3.create! valid_attributes
      expect {
        delete bar3_url(bar3)
      }.to change(Bar3, :count).by(-1)
    end

    it "redirects to the bar3s list" do
      bar3 = Bar3.create! valid_attributes
      delete bar3_url(bar3)
      expect(response).to redirect_to(bar3s_url)
    end
  end
end
