 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/bar44s", type: :request do
  
  # Bar44. As you add validations to Bar44, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Bar44.create! valid_attributes
      get bar44s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      bar44 = Bar44.create! valid_attributes
      get bar44_url(bar44)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_bar44_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      bar44 = Bar44.create! valid_attributes
      get edit_bar44_url(bar44)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Bar44" do
        expect {
          post bar44s_url, params: { bar44: valid_attributes }
        }.to change(Bar44, :count).by(1)
      end

      it "redirects to the created bar44" do
        post bar44s_url, params: { bar44: valid_attributes }
        expect(response).to redirect_to(bar44_url(Bar44.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Bar44" do
        expect {
          post bar44s_url, params: { bar44: invalid_attributes }
        }.to change(Bar44, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post bar44s_url, params: { bar44: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested bar44" do
        bar44 = Bar44.create! valid_attributes
        patch bar44_url(bar44), params: { bar44: new_attributes }
        bar44.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the bar44" do
        bar44 = Bar44.create! valid_attributes
        patch bar44_url(bar44), params: { bar44: new_attributes }
        bar44.reload
        expect(response).to redirect_to(bar44_url(bar44))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        bar44 = Bar44.create! valid_attributes
        patch bar44_url(bar44), params: { bar44: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested bar44" do
      bar44 = Bar44.create! valid_attributes
      expect {
        delete bar44_url(bar44)
      }.to change(Bar44, :count).by(-1)
    end

    it "redirects to the bar44s list" do
      bar44 = Bar44.create! valid_attributes
      delete bar44_url(bar44)
      expect(response).to redirect_to(bar44s_url)
    end
  end
end
