 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/bar47s", type: :request do
  
  # Bar47. As you add validations to Bar47, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Bar47.create! valid_attributes
      get bar47s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      bar47 = Bar47.create! valid_attributes
      get bar47_url(bar47)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_bar47_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      bar47 = Bar47.create! valid_attributes
      get edit_bar47_url(bar47)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Bar47" do
        expect {
          post bar47s_url, params: { bar47: valid_attributes }
        }.to change(Bar47, :count).by(1)
      end

      it "redirects to the created bar47" do
        post bar47s_url, params: { bar47: valid_attributes }
        expect(response).to redirect_to(bar47_url(Bar47.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Bar47" do
        expect {
          post bar47s_url, params: { bar47: invalid_attributes }
        }.to change(Bar47, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post bar47s_url, params: { bar47: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested bar47" do
        bar47 = Bar47.create! valid_attributes
        patch bar47_url(bar47), params: { bar47: new_attributes }
        bar47.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the bar47" do
        bar47 = Bar47.create! valid_attributes
        patch bar47_url(bar47), params: { bar47: new_attributes }
        bar47.reload
        expect(response).to redirect_to(bar47_url(bar47))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        bar47 = Bar47.create! valid_attributes
        patch bar47_url(bar47), params: { bar47: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested bar47" do
      bar47 = Bar47.create! valid_attributes
      expect {
        delete bar47_url(bar47)
      }.to change(Bar47, :count).by(-1)
    end

    it "redirects to the bar47s list" do
      bar47 = Bar47.create! valid_attributes
      delete bar47_url(bar47)
      expect(response).to redirect_to(bar47s_url)
    end
  end
end
