 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/bar40s", type: :request do
  
  # Bar40. As you add validations to Bar40, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Bar40.create! valid_attributes
      get bar40s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      bar40 = Bar40.create! valid_attributes
      get bar40_url(bar40)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_bar40_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      bar40 = Bar40.create! valid_attributes
      get edit_bar40_url(bar40)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Bar40" do
        expect {
          post bar40s_url, params: { bar40: valid_attributes }
        }.to change(Bar40, :count).by(1)
      end

      it "redirects to the created bar40" do
        post bar40s_url, params: { bar40: valid_attributes }
        expect(response).to redirect_to(bar40_url(Bar40.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Bar40" do
        expect {
          post bar40s_url, params: { bar40: invalid_attributes }
        }.to change(Bar40, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post bar40s_url, params: { bar40: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested bar40" do
        bar40 = Bar40.create! valid_attributes
        patch bar40_url(bar40), params: { bar40: new_attributes }
        bar40.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the bar40" do
        bar40 = Bar40.create! valid_attributes
        patch bar40_url(bar40), params: { bar40: new_attributes }
        bar40.reload
        expect(response).to redirect_to(bar40_url(bar40))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        bar40 = Bar40.create! valid_attributes
        patch bar40_url(bar40), params: { bar40: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested bar40" do
      bar40 = Bar40.create! valid_attributes
      expect {
        delete bar40_url(bar40)
      }.to change(Bar40, :count).by(-1)
    end

    it "redirects to the bar40s list" do
      bar40 = Bar40.create! valid_attributes
      delete bar40_url(bar40)
      expect(response).to redirect_to(bar40s_url)
    end
  end
end
