 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/bar43s", type: :request do
  
  # Bar43. As you add validations to Bar43, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Bar43.create! valid_attributes
      get bar43s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      bar43 = Bar43.create! valid_attributes
      get bar43_url(bar43)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_bar43_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      bar43 = Bar43.create! valid_attributes
      get edit_bar43_url(bar43)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Bar43" do
        expect {
          post bar43s_url, params: { bar43: valid_attributes }
        }.to change(Bar43, :count).by(1)
      end

      it "redirects to the created bar43" do
        post bar43s_url, params: { bar43: valid_attributes }
        expect(response).to redirect_to(bar43_url(Bar43.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Bar43" do
        expect {
          post bar43s_url, params: { bar43: invalid_attributes }
        }.to change(Bar43, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post bar43s_url, params: { bar43: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested bar43" do
        bar43 = Bar43.create! valid_attributes
        patch bar43_url(bar43), params: { bar43: new_attributes }
        bar43.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the bar43" do
        bar43 = Bar43.create! valid_attributes
        patch bar43_url(bar43), params: { bar43: new_attributes }
        bar43.reload
        expect(response).to redirect_to(bar43_url(bar43))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        bar43 = Bar43.create! valid_attributes
        patch bar43_url(bar43), params: { bar43: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested bar43" do
      bar43 = Bar43.create! valid_attributes
      expect {
        delete bar43_url(bar43)
      }.to change(Bar43, :count).by(-1)
    end

    it "redirects to the bar43s list" do
      bar43 = Bar43.create! valid_attributes
      delete bar43_url(bar43)
      expect(response).to redirect_to(bar43s_url)
    end
  end
end
