 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/bar5s", type: :request do
  
  # Bar5. As you add validations to Bar5, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Bar5.create! valid_attributes
      get bar5s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      bar5 = Bar5.create! valid_attributes
      get bar5_url(bar5)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_bar5_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      bar5 = Bar5.create! valid_attributes
      get edit_bar5_url(bar5)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Bar5" do
        expect {
          post bar5s_url, params: { bar5: valid_attributes }
        }.to change(Bar5, :count).by(1)
      end

      it "redirects to the created bar5" do
        post bar5s_url, params: { bar5: valid_attributes }
        expect(response).to redirect_to(bar5_url(Bar5.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Bar5" do
        expect {
          post bar5s_url, params: { bar5: invalid_attributes }
        }.to change(Bar5, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post bar5s_url, params: { bar5: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested bar5" do
        bar5 = Bar5.create! valid_attributes
        patch bar5_url(bar5), params: { bar5: new_attributes }
        bar5.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the bar5" do
        bar5 = Bar5.create! valid_attributes
        patch bar5_url(bar5), params: { bar5: new_attributes }
        bar5.reload
        expect(response).to redirect_to(bar5_url(bar5))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        bar5 = Bar5.create! valid_attributes
        patch bar5_url(bar5), params: { bar5: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested bar5" do
      bar5 = Bar5.create! valid_attributes
      expect {
        delete bar5_url(bar5)
      }.to change(Bar5, :count).by(-1)
    end

    it "redirects to the bar5s list" do
      bar5 = Bar5.create! valid_attributes
      delete bar5_url(bar5)
      expect(response).to redirect_to(bar5s_url)
    end
  end
end
