 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/bar59s", type: :request do
  
  # Bar59. As you add validations to Bar59, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Bar59.create! valid_attributes
      get bar59s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      bar59 = Bar59.create! valid_attributes
      get bar59_url(bar59)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_bar59_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      bar59 = Bar59.create! valid_attributes
      get edit_bar59_url(bar59)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Bar59" do
        expect {
          post bar59s_url, params: { bar59: valid_attributes }
        }.to change(Bar59, :count).by(1)
      end

      it "redirects to the created bar59" do
        post bar59s_url, params: { bar59: valid_attributes }
        expect(response).to redirect_to(bar59_url(Bar59.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Bar59" do
        expect {
          post bar59s_url, params: { bar59: invalid_attributes }
        }.to change(Bar59, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post bar59s_url, params: { bar59: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested bar59" do
        bar59 = Bar59.create! valid_attributes
        patch bar59_url(bar59), params: { bar59: new_attributes }
        bar59.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the bar59" do
        bar59 = Bar59.create! valid_attributes
        patch bar59_url(bar59), params: { bar59: new_attributes }
        bar59.reload
        expect(response).to redirect_to(bar59_url(bar59))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        bar59 = Bar59.create! valid_attributes
        patch bar59_url(bar59), params: { bar59: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested bar59" do
      bar59 = Bar59.create! valid_attributes
      expect {
        delete bar59_url(bar59)
      }.to change(Bar59, :count).by(-1)
    end

    it "redirects to the bar59s list" do
      bar59 = Bar59.create! valid_attributes
      delete bar59_url(bar59)
      expect(response).to redirect_to(bar59s_url)
    end
  end
end
