 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/bar73s", type: :request do
  
  # Bar73. As you add validations to Bar73, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Bar73.create! valid_attributes
      get bar73s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      bar73 = Bar73.create! valid_attributes
      get bar73_url(bar73)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_bar73_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      bar73 = Bar73.create! valid_attributes
      get edit_bar73_url(bar73)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Bar73" do
        expect {
          post bar73s_url, params: { bar73: valid_attributes }
        }.to change(Bar73, :count).by(1)
      end

      it "redirects to the created bar73" do
        post bar73s_url, params: { bar73: valid_attributes }
        expect(response).to redirect_to(bar73_url(Bar73.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Bar73" do
        expect {
          post bar73s_url, params: { bar73: invalid_attributes }
        }.to change(Bar73, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post bar73s_url, params: { bar73: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested bar73" do
        bar73 = Bar73.create! valid_attributes
        patch bar73_url(bar73), params: { bar73: new_attributes }
        bar73.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the bar73" do
        bar73 = Bar73.create! valid_attributes
        patch bar73_url(bar73), params: { bar73: new_attributes }
        bar73.reload
        expect(response).to redirect_to(bar73_url(bar73))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        bar73 = Bar73.create! valid_attributes
        patch bar73_url(bar73), params: { bar73: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested bar73" do
      bar73 = Bar73.create! valid_attributes
      expect {
        delete bar73_url(bar73)
      }.to change(Bar73, :count).by(-1)
    end

    it "redirects to the bar73s list" do
      bar73 = Bar73.create! valid_attributes
      delete bar73_url(bar73)
      expect(response).to redirect_to(bar73s_url)
    end
  end
end
