 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/bar79s", type: :request do
  
  # Bar79. As you add validations to Bar79, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Bar79.create! valid_attributes
      get bar79s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      bar79 = Bar79.create! valid_attributes
      get bar79_url(bar79)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_bar79_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      bar79 = Bar79.create! valid_attributes
      get edit_bar79_url(bar79)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Bar79" do
        expect {
          post bar79s_url, params: { bar79: valid_attributes }
        }.to change(Bar79, :count).by(1)
      end

      it "redirects to the created bar79" do
        post bar79s_url, params: { bar79: valid_attributes }
        expect(response).to redirect_to(bar79_url(Bar79.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Bar79" do
        expect {
          post bar79s_url, params: { bar79: invalid_attributes }
        }.to change(Bar79, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post bar79s_url, params: { bar79: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested bar79" do
        bar79 = Bar79.create! valid_attributes
        patch bar79_url(bar79), params: { bar79: new_attributes }
        bar79.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the bar79" do
        bar79 = Bar79.create! valid_attributes
        patch bar79_url(bar79), params: { bar79: new_attributes }
        bar79.reload
        expect(response).to redirect_to(bar79_url(bar79))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        bar79 = Bar79.create! valid_attributes
        patch bar79_url(bar79), params: { bar79: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested bar79" do
      bar79 = Bar79.create! valid_attributes
      expect {
        delete bar79_url(bar79)
      }.to change(Bar79, :count).by(-1)
    end

    it "redirects to the bar79s list" do
      bar79 = Bar79.create! valid_attributes
      delete bar79_url(bar79)
      expect(response).to redirect_to(bar79s_url)
    end
  end
end
