 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/baz10s", type: :request do
  
  # Baz10. As you add validations to Baz10, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Baz10.create! valid_attributes
      get baz10s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      baz10 = Baz10.create! valid_attributes
      get baz10_url(baz10)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_baz10_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      baz10 = Baz10.create! valid_attributes
      get edit_baz10_url(baz10)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Baz10" do
        expect {
          post baz10s_url, params: { baz10: valid_attributes }
        }.to change(Baz10, :count).by(1)
      end

      it "redirects to the created baz10" do
        post baz10s_url, params: { baz10: valid_attributes }
        expect(response).to redirect_to(baz10_url(Baz10.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Baz10" do
        expect {
          post baz10s_url, params: { baz10: invalid_attributes }
        }.to change(Baz10, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post baz10s_url, params: { baz10: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested baz10" do
        baz10 = Baz10.create! valid_attributes
        patch baz10_url(baz10), params: { baz10: new_attributes }
        baz10.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the baz10" do
        baz10 = Baz10.create! valid_attributes
        patch baz10_url(baz10), params: { baz10: new_attributes }
        baz10.reload
        expect(response).to redirect_to(baz10_url(baz10))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        baz10 = Baz10.create! valid_attributes
        patch baz10_url(baz10), params: { baz10: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested baz10" do
      baz10 = Baz10.create! valid_attributes
      expect {
        delete baz10_url(baz10)
      }.to change(Baz10, :count).by(-1)
    end

    it "redirects to the baz10s list" do
      baz10 = Baz10.create! valid_attributes
      delete baz10_url(baz10)
      expect(response).to redirect_to(baz10s_url)
    end
  end
end
