 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/baz18s", type: :request do
  
  # Baz18. As you add validations to Baz18, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Baz18.create! valid_attributes
      get baz18s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      baz18 = Baz18.create! valid_attributes
      get baz18_url(baz18)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_baz18_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      baz18 = Baz18.create! valid_attributes
      get edit_baz18_url(baz18)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Baz18" do
        expect {
          post baz18s_url, params: { baz18: valid_attributes }
        }.to change(Baz18, :count).by(1)
      end

      it "redirects to the created baz18" do
        post baz18s_url, params: { baz18: valid_attributes }
        expect(response).to redirect_to(baz18_url(Baz18.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Baz18" do
        expect {
          post baz18s_url, params: { baz18: invalid_attributes }
        }.to change(Baz18, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post baz18s_url, params: { baz18: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested baz18" do
        baz18 = Baz18.create! valid_attributes
        patch baz18_url(baz18), params: { baz18: new_attributes }
        baz18.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the baz18" do
        baz18 = Baz18.create! valid_attributes
        patch baz18_url(baz18), params: { baz18: new_attributes }
        baz18.reload
        expect(response).to redirect_to(baz18_url(baz18))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        baz18 = Baz18.create! valid_attributes
        patch baz18_url(baz18), params: { baz18: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested baz18" do
      baz18 = Baz18.create! valid_attributes
      expect {
        delete baz18_url(baz18)
      }.to change(Baz18, :count).by(-1)
    end

    it "redirects to the baz18s list" do
      baz18 = Baz18.create! valid_attributes
      delete baz18_url(baz18)
      expect(response).to redirect_to(baz18s_url)
    end
  end
end
