 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/baz13s", type: :request do
  
  # Baz13. As you add validations to Baz13, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Baz13.create! valid_attributes
      get baz13s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      baz13 = Baz13.create! valid_attributes
      get baz13_url(baz13)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_baz13_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      baz13 = Baz13.create! valid_attributes
      get edit_baz13_url(baz13)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Baz13" do
        expect {
          post baz13s_url, params: { baz13: valid_attributes }
        }.to change(Baz13, :count).by(1)
      end

      it "redirects to the created baz13" do
        post baz13s_url, params: { baz13: valid_attributes }
        expect(response).to redirect_to(baz13_url(Baz13.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Baz13" do
        expect {
          post baz13s_url, params: { baz13: invalid_attributes }
        }.to change(Baz13, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post baz13s_url, params: { baz13: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested baz13" do
        baz13 = Baz13.create! valid_attributes
        patch baz13_url(baz13), params: { baz13: new_attributes }
        baz13.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the baz13" do
        baz13 = Baz13.create! valid_attributes
        patch baz13_url(baz13), params: { baz13: new_attributes }
        baz13.reload
        expect(response).to redirect_to(baz13_url(baz13))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        baz13 = Baz13.create! valid_attributes
        patch baz13_url(baz13), params: { baz13: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested baz13" do
      baz13 = Baz13.create! valid_attributes
      expect {
        delete baz13_url(baz13)
      }.to change(Baz13, :count).by(-1)
    end

    it "redirects to the baz13s list" do
      baz13 = Baz13.create! valid_attributes
      delete baz13_url(baz13)
      expect(response).to redirect_to(baz13s_url)
    end
  end
end
