 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/baz19s", type: :request do
  
  # Baz19. As you add validations to Baz19, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Baz19.create! valid_attributes
      get baz19s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      baz19 = Baz19.create! valid_attributes
      get baz19_url(baz19)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_baz19_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      baz19 = Baz19.create! valid_attributes
      get edit_baz19_url(baz19)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Baz19" do
        expect {
          post baz19s_url, params: { baz19: valid_attributes }
        }.to change(Baz19, :count).by(1)
      end

      it "redirects to the created baz19" do
        post baz19s_url, params: { baz19: valid_attributes }
        expect(response).to redirect_to(baz19_url(Baz19.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Baz19" do
        expect {
          post baz19s_url, params: { baz19: invalid_attributes }
        }.to change(Baz19, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post baz19s_url, params: { baz19: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested baz19" do
        baz19 = Baz19.create! valid_attributes
        patch baz19_url(baz19), params: { baz19: new_attributes }
        baz19.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the baz19" do
        baz19 = Baz19.create! valid_attributes
        patch baz19_url(baz19), params: { baz19: new_attributes }
        baz19.reload
        expect(response).to redirect_to(baz19_url(baz19))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        baz19 = Baz19.create! valid_attributes
        patch baz19_url(baz19), params: { baz19: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested baz19" do
      baz19 = Baz19.create! valid_attributes
      expect {
        delete baz19_url(baz19)
      }.to change(Baz19, :count).by(-1)
    end

    it "redirects to the baz19s list" do
      baz19 = Baz19.create! valid_attributes
      delete baz19_url(baz19)
      expect(response).to redirect_to(baz19s_url)
    end
  end
end
