 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/baz100s", type: :request do
  
  # Baz100. As you add validations to Baz100, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Baz100.create! valid_attributes
      get baz100s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      baz100 = Baz100.create! valid_attributes
      get baz100_url(baz100)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_baz100_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      baz100 = Baz100.create! valid_attributes
      get edit_baz100_url(baz100)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Baz100" do
        expect {
          post baz100s_url, params: { baz100: valid_attributes }
        }.to change(Baz100, :count).by(1)
      end

      it "redirects to the created baz100" do
        post baz100s_url, params: { baz100: valid_attributes }
        expect(response).to redirect_to(baz100_url(Baz100.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Baz100" do
        expect {
          post baz100s_url, params: { baz100: invalid_attributes }
        }.to change(Baz100, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post baz100s_url, params: { baz100: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested baz100" do
        baz100 = Baz100.create! valid_attributes
        patch baz100_url(baz100), params: { baz100: new_attributes }
        baz100.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the baz100" do
        baz100 = Baz100.create! valid_attributes
        patch baz100_url(baz100), params: { baz100: new_attributes }
        baz100.reload
        expect(response).to redirect_to(baz100_url(baz100))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        baz100 = Baz100.create! valid_attributes
        patch baz100_url(baz100), params: { baz100: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested baz100" do
      baz100 = Baz100.create! valid_attributes
      expect {
        delete baz100_url(baz100)
      }.to change(Baz100, :count).by(-1)
    end

    it "redirects to the baz100s list" do
      baz100 = Baz100.create! valid_attributes
      delete baz100_url(baz100)
      expect(response).to redirect_to(baz100s_url)
    end
  end
end
