 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/baz23s", type: :request do
  
  # Baz23. As you add validations to Baz23, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Baz23.create! valid_attributes
      get baz23s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      baz23 = Baz23.create! valid_attributes
      get baz23_url(baz23)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_baz23_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      baz23 = Baz23.create! valid_attributes
      get edit_baz23_url(baz23)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Baz23" do
        expect {
          post baz23s_url, params: { baz23: valid_attributes }
        }.to change(Baz23, :count).by(1)
      end

      it "redirects to the created baz23" do
        post baz23s_url, params: { baz23: valid_attributes }
        expect(response).to redirect_to(baz23_url(Baz23.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Baz23" do
        expect {
          post baz23s_url, params: { baz23: invalid_attributes }
        }.to change(Baz23, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post baz23s_url, params: { baz23: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested baz23" do
        baz23 = Baz23.create! valid_attributes
        patch baz23_url(baz23), params: { baz23: new_attributes }
        baz23.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the baz23" do
        baz23 = Baz23.create! valid_attributes
        patch baz23_url(baz23), params: { baz23: new_attributes }
        baz23.reload
        expect(response).to redirect_to(baz23_url(baz23))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        baz23 = Baz23.create! valid_attributes
        patch baz23_url(baz23), params: { baz23: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested baz23" do
      baz23 = Baz23.create! valid_attributes
      expect {
        delete baz23_url(baz23)
      }.to change(Baz23, :count).by(-1)
    end

    it "redirects to the baz23s list" do
      baz23 = Baz23.create! valid_attributes
      delete baz23_url(baz23)
      expect(response).to redirect_to(baz23s_url)
    end
  end
end
