 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/baz21s", type: :request do
  
  # Baz21. As you add validations to Baz21, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Baz21.create! valid_attributes
      get baz21s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      baz21 = Baz21.create! valid_attributes
      get baz21_url(baz21)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_baz21_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      baz21 = Baz21.create! valid_attributes
      get edit_baz21_url(baz21)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Baz21" do
        expect {
          post baz21s_url, params: { baz21: valid_attributes }
        }.to change(Baz21, :count).by(1)
      end

      it "redirects to the created baz21" do
        post baz21s_url, params: { baz21: valid_attributes }
        expect(response).to redirect_to(baz21_url(Baz21.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Baz21" do
        expect {
          post baz21s_url, params: { baz21: invalid_attributes }
        }.to change(Baz21, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post baz21s_url, params: { baz21: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested baz21" do
        baz21 = Baz21.create! valid_attributes
        patch baz21_url(baz21), params: { baz21: new_attributes }
        baz21.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the baz21" do
        baz21 = Baz21.create! valid_attributes
        patch baz21_url(baz21), params: { baz21: new_attributes }
        baz21.reload
        expect(response).to redirect_to(baz21_url(baz21))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        baz21 = Baz21.create! valid_attributes
        patch baz21_url(baz21), params: { baz21: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested baz21" do
      baz21 = Baz21.create! valid_attributes
      expect {
        delete baz21_url(baz21)
      }.to change(Baz21, :count).by(-1)
    end

    it "redirects to the baz21s list" do
      baz21 = Baz21.create! valid_attributes
      delete baz21_url(baz21)
      expect(response).to redirect_to(baz21s_url)
    end
  end
end
