 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/baz51s", type: :request do
  
  # Baz51. As you add validations to Baz51, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Baz51.create! valid_attributes
      get baz51s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      baz51 = Baz51.create! valid_attributes
      get baz51_url(baz51)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_baz51_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      baz51 = Baz51.create! valid_attributes
      get edit_baz51_url(baz51)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Baz51" do
        expect {
          post baz51s_url, params: { baz51: valid_attributes }
        }.to change(Baz51, :count).by(1)
      end

      it "redirects to the created baz51" do
        post baz51s_url, params: { baz51: valid_attributes }
        expect(response).to redirect_to(baz51_url(Baz51.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Baz51" do
        expect {
          post baz51s_url, params: { baz51: invalid_attributes }
        }.to change(Baz51, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post baz51s_url, params: { baz51: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested baz51" do
        baz51 = Baz51.create! valid_attributes
        patch baz51_url(baz51), params: { baz51: new_attributes }
        baz51.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the baz51" do
        baz51 = Baz51.create! valid_attributes
        patch baz51_url(baz51), params: { baz51: new_attributes }
        baz51.reload
        expect(response).to redirect_to(baz51_url(baz51))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        baz51 = Baz51.create! valid_attributes
        patch baz51_url(baz51), params: { baz51: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested baz51" do
      baz51 = Baz51.create! valid_attributes
      expect {
        delete baz51_url(baz51)
      }.to change(Baz51, :count).by(-1)
    end

    it "redirects to the baz51s list" do
      baz51 = Baz51.create! valid_attributes
      delete baz51_url(baz51)
      expect(response).to redirect_to(baz51s_url)
    end
  end
end
