 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/baz67s", type: :request do
  
  # Baz67. As you add validations to Baz67, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Baz67.create! valid_attributes
      get baz67s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      baz67 = Baz67.create! valid_attributes
      get baz67_url(baz67)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_baz67_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      baz67 = Baz67.create! valid_attributes
      get edit_baz67_url(baz67)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Baz67" do
        expect {
          post baz67s_url, params: { baz67: valid_attributes }
        }.to change(Baz67, :count).by(1)
      end

      it "redirects to the created baz67" do
        post baz67s_url, params: { baz67: valid_attributes }
        expect(response).to redirect_to(baz67_url(Baz67.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Baz67" do
        expect {
          post baz67s_url, params: { baz67: invalid_attributes }
        }.to change(Baz67, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post baz67s_url, params: { baz67: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested baz67" do
        baz67 = Baz67.create! valid_attributes
        patch baz67_url(baz67), params: { baz67: new_attributes }
        baz67.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the baz67" do
        baz67 = Baz67.create! valid_attributes
        patch baz67_url(baz67), params: { baz67: new_attributes }
        baz67.reload
        expect(response).to redirect_to(baz67_url(baz67))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        baz67 = Baz67.create! valid_attributes
        patch baz67_url(baz67), params: { baz67: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested baz67" do
      baz67 = Baz67.create! valid_attributes
      expect {
        delete baz67_url(baz67)
      }.to change(Baz67, :count).by(-1)
    end

    it "redirects to the baz67s list" do
      baz67 = Baz67.create! valid_attributes
      delete baz67_url(baz67)
      expect(response).to redirect_to(baz67s_url)
    end
  end
end
