 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/baz60s", type: :request do
  
  # Baz60. As you add validations to Baz60, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Baz60.create! valid_attributes
      get baz60s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      baz60 = Baz60.create! valid_attributes
      get baz60_url(baz60)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_baz60_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      baz60 = Baz60.create! valid_attributes
      get edit_baz60_url(baz60)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Baz60" do
        expect {
          post baz60s_url, params: { baz60: valid_attributes }
        }.to change(Baz60, :count).by(1)
      end

      it "redirects to the created baz60" do
        post baz60s_url, params: { baz60: valid_attributes }
        expect(response).to redirect_to(baz60_url(Baz60.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Baz60" do
        expect {
          post baz60s_url, params: { baz60: invalid_attributes }
        }.to change(Baz60, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post baz60s_url, params: { baz60: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested baz60" do
        baz60 = Baz60.create! valid_attributes
        patch baz60_url(baz60), params: { baz60: new_attributes }
        baz60.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the baz60" do
        baz60 = Baz60.create! valid_attributes
        patch baz60_url(baz60), params: { baz60: new_attributes }
        baz60.reload
        expect(response).to redirect_to(baz60_url(baz60))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        baz60 = Baz60.create! valid_attributes
        patch baz60_url(baz60), params: { baz60: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested baz60" do
      baz60 = Baz60.create! valid_attributes
      expect {
        delete baz60_url(baz60)
      }.to change(Baz60, :count).by(-1)
    end

    it "redirects to the baz60s list" do
      baz60 = Baz60.create! valid_attributes
      delete baz60_url(baz60)
      expect(response).to redirect_to(baz60s_url)
    end
  end
end
