 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/baz63s", type: :request do
  
  # Baz63. As you add validations to Baz63, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Baz63.create! valid_attributes
      get baz63s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      baz63 = Baz63.create! valid_attributes
      get baz63_url(baz63)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_baz63_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      baz63 = Baz63.create! valid_attributes
      get edit_baz63_url(baz63)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Baz63" do
        expect {
          post baz63s_url, params: { baz63: valid_attributes }
        }.to change(Baz63, :count).by(1)
      end

      it "redirects to the created baz63" do
        post baz63s_url, params: { baz63: valid_attributes }
        expect(response).to redirect_to(baz63_url(Baz63.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Baz63" do
        expect {
          post baz63s_url, params: { baz63: invalid_attributes }
        }.to change(Baz63, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post baz63s_url, params: { baz63: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested baz63" do
        baz63 = Baz63.create! valid_attributes
        patch baz63_url(baz63), params: { baz63: new_attributes }
        baz63.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the baz63" do
        baz63 = Baz63.create! valid_attributes
        patch baz63_url(baz63), params: { baz63: new_attributes }
        baz63.reload
        expect(response).to redirect_to(baz63_url(baz63))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        baz63 = Baz63.create! valid_attributes
        patch baz63_url(baz63), params: { baz63: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested baz63" do
      baz63 = Baz63.create! valid_attributes
      expect {
        delete baz63_url(baz63)
      }.to change(Baz63, :count).by(-1)
    end

    it "redirects to the baz63s list" do
      baz63 = Baz63.create! valid_attributes
      delete baz63_url(baz63)
      expect(response).to redirect_to(baz63s_url)
    end
  end
end
