 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/baz65s", type: :request do
  
  # Baz65. As you add validations to Baz65, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Baz65.create! valid_attributes
      get baz65s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      baz65 = Baz65.create! valid_attributes
      get baz65_url(baz65)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_baz65_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      baz65 = Baz65.create! valid_attributes
      get edit_baz65_url(baz65)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Baz65" do
        expect {
          post baz65s_url, params: { baz65: valid_attributes }
        }.to change(Baz65, :count).by(1)
      end

      it "redirects to the created baz65" do
        post baz65s_url, params: { baz65: valid_attributes }
        expect(response).to redirect_to(baz65_url(Baz65.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Baz65" do
        expect {
          post baz65s_url, params: { baz65: invalid_attributes }
        }.to change(Baz65, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post baz65s_url, params: { baz65: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested baz65" do
        baz65 = Baz65.create! valid_attributes
        patch baz65_url(baz65), params: { baz65: new_attributes }
        baz65.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the baz65" do
        baz65 = Baz65.create! valid_attributes
        patch baz65_url(baz65), params: { baz65: new_attributes }
        baz65.reload
        expect(response).to redirect_to(baz65_url(baz65))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        baz65 = Baz65.create! valid_attributes
        patch baz65_url(baz65), params: { baz65: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested baz65" do
      baz65 = Baz65.create! valid_attributes
      expect {
        delete baz65_url(baz65)
      }.to change(Baz65, :count).by(-1)
    end

    it "redirects to the baz65s list" do
      baz65 = Baz65.create! valid_attributes
      delete baz65_url(baz65)
      expect(response).to redirect_to(baz65s_url)
    end
  end
end
