 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/baz77s", type: :request do
  
  # Baz77. As you add validations to Baz77, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Baz77.create! valid_attributes
      get baz77s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      baz77 = Baz77.create! valid_attributes
      get baz77_url(baz77)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_baz77_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      baz77 = Baz77.create! valid_attributes
      get edit_baz77_url(baz77)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Baz77" do
        expect {
          post baz77s_url, params: { baz77: valid_attributes }
        }.to change(Baz77, :count).by(1)
      end

      it "redirects to the created baz77" do
        post baz77s_url, params: { baz77: valid_attributes }
        expect(response).to redirect_to(baz77_url(Baz77.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Baz77" do
        expect {
          post baz77s_url, params: { baz77: invalid_attributes }
        }.to change(Baz77, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post baz77s_url, params: { baz77: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested baz77" do
        baz77 = Baz77.create! valid_attributes
        patch baz77_url(baz77), params: { baz77: new_attributes }
        baz77.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the baz77" do
        baz77 = Baz77.create! valid_attributes
        patch baz77_url(baz77), params: { baz77: new_attributes }
        baz77.reload
        expect(response).to redirect_to(baz77_url(baz77))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        baz77 = Baz77.create! valid_attributes
        patch baz77_url(baz77), params: { baz77: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested baz77" do
      baz77 = Baz77.create! valid_attributes
      expect {
        delete baz77_url(baz77)
      }.to change(Baz77, :count).by(-1)
    end

    it "redirects to the baz77s list" do
      baz77 = Baz77.create! valid_attributes
      delete baz77_url(baz77)
      expect(response).to redirect_to(baz77s_url)
    end
  end
end
