 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/baz70s", type: :request do
  
  # Baz70. As you add validations to Baz70, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Baz70.create! valid_attributes
      get baz70s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      baz70 = Baz70.create! valid_attributes
      get baz70_url(baz70)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_baz70_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      baz70 = Baz70.create! valid_attributes
      get edit_baz70_url(baz70)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Baz70" do
        expect {
          post baz70s_url, params: { baz70: valid_attributes }
        }.to change(Baz70, :count).by(1)
      end

      it "redirects to the created baz70" do
        post baz70s_url, params: { baz70: valid_attributes }
        expect(response).to redirect_to(baz70_url(Baz70.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Baz70" do
        expect {
          post baz70s_url, params: { baz70: invalid_attributes }
        }.to change(Baz70, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post baz70s_url, params: { baz70: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested baz70" do
        baz70 = Baz70.create! valid_attributes
        patch baz70_url(baz70), params: { baz70: new_attributes }
        baz70.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the baz70" do
        baz70 = Baz70.create! valid_attributes
        patch baz70_url(baz70), params: { baz70: new_attributes }
        baz70.reload
        expect(response).to redirect_to(baz70_url(baz70))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        baz70 = Baz70.create! valid_attributes
        patch baz70_url(baz70), params: { baz70: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested baz70" do
      baz70 = Baz70.create! valid_attributes
      expect {
        delete baz70_url(baz70)
      }.to change(Baz70, :count).by(-1)
    end

    it "redirects to the baz70s list" do
      baz70 = Baz70.create! valid_attributes
      delete baz70_url(baz70)
      expect(response).to redirect_to(baz70s_url)
    end
  end
end
