 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/baz74s", type: :request do
  
  # Baz74. As you add validations to Baz74, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Baz74.create! valid_attributes
      get baz74s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      baz74 = Baz74.create! valid_attributes
      get baz74_url(baz74)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_baz74_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      baz74 = Baz74.create! valid_attributes
      get edit_baz74_url(baz74)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Baz74" do
        expect {
          post baz74s_url, params: { baz74: valid_attributes }
        }.to change(Baz74, :count).by(1)
      end

      it "redirects to the created baz74" do
        post baz74s_url, params: { baz74: valid_attributes }
        expect(response).to redirect_to(baz74_url(Baz74.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Baz74" do
        expect {
          post baz74s_url, params: { baz74: invalid_attributes }
        }.to change(Baz74, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post baz74s_url, params: { baz74: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested baz74" do
        baz74 = Baz74.create! valid_attributes
        patch baz74_url(baz74), params: { baz74: new_attributes }
        baz74.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the baz74" do
        baz74 = Baz74.create! valid_attributes
        patch baz74_url(baz74), params: { baz74: new_attributes }
        baz74.reload
        expect(response).to redirect_to(baz74_url(baz74))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        baz74 = Baz74.create! valid_attributes
        patch baz74_url(baz74), params: { baz74: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested baz74" do
      baz74 = Baz74.create! valid_attributes
      expect {
        delete baz74_url(baz74)
      }.to change(Baz74, :count).by(-1)
    end

    it "redirects to the baz74s list" do
      baz74 = Baz74.create! valid_attributes
      delete baz74_url(baz74)
      expect(response).to redirect_to(baz74s_url)
    end
  end
end
