 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/baz79s", type: :request do
  
  # Baz79. As you add validations to Baz79, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Baz79.create! valid_attributes
      get baz79s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      baz79 = Baz79.create! valid_attributes
      get baz79_url(baz79)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_baz79_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      baz79 = Baz79.create! valid_attributes
      get edit_baz79_url(baz79)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Baz79" do
        expect {
          post baz79s_url, params: { baz79: valid_attributes }
        }.to change(Baz79, :count).by(1)
      end

      it "redirects to the created baz79" do
        post baz79s_url, params: { baz79: valid_attributes }
        expect(response).to redirect_to(baz79_url(Baz79.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Baz79" do
        expect {
          post baz79s_url, params: { baz79: invalid_attributes }
        }.to change(Baz79, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post baz79s_url, params: { baz79: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested baz79" do
        baz79 = Baz79.create! valid_attributes
        patch baz79_url(baz79), params: { baz79: new_attributes }
        baz79.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the baz79" do
        baz79 = Baz79.create! valid_attributes
        patch baz79_url(baz79), params: { baz79: new_attributes }
        baz79.reload
        expect(response).to redirect_to(baz79_url(baz79))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        baz79 = Baz79.create! valid_attributes
        patch baz79_url(baz79), params: { baz79: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested baz79" do
      baz79 = Baz79.create! valid_attributes
      expect {
        delete baz79_url(baz79)
      }.to change(Baz79, :count).by(-1)
    end

    it "redirects to the baz79s list" do
      baz79 = Baz79.create! valid_attributes
      delete baz79_url(baz79)
      expect(response).to redirect_to(baz79s_url)
    end
  end
end
