 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/baz8s", type: :request do
  
  # Baz8. As you add validations to Baz8, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Baz8.create! valid_attributes
      get baz8s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      baz8 = Baz8.create! valid_attributes
      get baz8_url(baz8)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_baz8_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      baz8 = Baz8.create! valid_attributes
      get edit_baz8_url(baz8)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Baz8" do
        expect {
          post baz8s_url, params: { baz8: valid_attributes }
        }.to change(Baz8, :count).by(1)
      end

      it "redirects to the created baz8" do
        post baz8s_url, params: { baz8: valid_attributes }
        expect(response).to redirect_to(baz8_url(Baz8.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Baz8" do
        expect {
          post baz8s_url, params: { baz8: invalid_attributes }
        }.to change(Baz8, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post baz8s_url, params: { baz8: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested baz8" do
        baz8 = Baz8.create! valid_attributes
        patch baz8_url(baz8), params: { baz8: new_attributes }
        baz8.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the baz8" do
        baz8 = Baz8.create! valid_attributes
        patch baz8_url(baz8), params: { baz8: new_attributes }
        baz8.reload
        expect(response).to redirect_to(baz8_url(baz8))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        baz8 = Baz8.create! valid_attributes
        patch baz8_url(baz8), params: { baz8: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested baz8" do
      baz8 = Baz8.create! valid_attributes
      expect {
        delete baz8_url(baz8)
      }.to change(Baz8, :count).by(-1)
    end

    it "redirects to the baz8s list" do
      baz8 = Baz8.create! valid_attributes
      delete baz8_url(baz8)
      expect(response).to redirect_to(baz8s_url)
    end
  end
end
