 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/baz89s", type: :request do
  
  # Baz89. As you add validations to Baz89, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Baz89.create! valid_attributes
      get baz89s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      baz89 = Baz89.create! valid_attributes
      get baz89_url(baz89)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_baz89_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      baz89 = Baz89.create! valid_attributes
      get edit_baz89_url(baz89)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Baz89" do
        expect {
          post baz89s_url, params: { baz89: valid_attributes }
        }.to change(Baz89, :count).by(1)
      end

      it "redirects to the created baz89" do
        post baz89s_url, params: { baz89: valid_attributes }
        expect(response).to redirect_to(baz89_url(Baz89.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Baz89" do
        expect {
          post baz89s_url, params: { baz89: invalid_attributes }
        }.to change(Baz89, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post baz89s_url, params: { baz89: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested baz89" do
        baz89 = Baz89.create! valid_attributes
        patch baz89_url(baz89), params: { baz89: new_attributes }
        baz89.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the baz89" do
        baz89 = Baz89.create! valid_attributes
        patch baz89_url(baz89), params: { baz89: new_attributes }
        baz89.reload
        expect(response).to redirect_to(baz89_url(baz89))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        baz89 = Baz89.create! valid_attributes
        patch baz89_url(baz89), params: { baz89: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested baz89" do
      baz89 = Baz89.create! valid_attributes
      expect {
        delete baz89_url(baz89)
      }.to change(Baz89, :count).by(-1)
    end

    it "redirects to the baz89s list" do
      baz89 = Baz89.create! valid_attributes
      delete baz89_url(baz89)
      expect(response).to redirect_to(baz89s_url)
    end
  end
end
