 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/baz94s", type: :request do
  
  # Baz94. As you add validations to Baz94, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Baz94.create! valid_attributes
      get baz94s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      baz94 = Baz94.create! valid_attributes
      get baz94_url(baz94)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_baz94_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      baz94 = Baz94.create! valid_attributes
      get edit_baz94_url(baz94)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Baz94" do
        expect {
          post baz94s_url, params: { baz94: valid_attributes }
        }.to change(Baz94, :count).by(1)
      end

      it "redirects to the created baz94" do
        post baz94s_url, params: { baz94: valid_attributes }
        expect(response).to redirect_to(baz94_url(Baz94.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Baz94" do
        expect {
          post baz94s_url, params: { baz94: invalid_attributes }
        }.to change(Baz94, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post baz94s_url, params: { baz94: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested baz94" do
        baz94 = Baz94.create! valid_attributes
        patch baz94_url(baz94), params: { baz94: new_attributes }
        baz94.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the baz94" do
        baz94 = Baz94.create! valid_attributes
        patch baz94_url(baz94), params: { baz94: new_attributes }
        baz94.reload
        expect(response).to redirect_to(baz94_url(baz94))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        baz94 = Baz94.create! valid_attributes
        patch baz94_url(baz94), params: { baz94: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested baz94" do
      baz94 = Baz94.create! valid_attributes
      expect {
        delete baz94_url(baz94)
      }.to change(Baz94, :count).by(-1)
    end

    it "redirects to the baz94s list" do
      baz94 = Baz94.create! valid_attributes
      delete baz94_url(baz94)
      expect(response).to redirect_to(baz94s_url)
    end
  end
end
