Rails.application.routes.draw do
  resources :foo100s
  resources :foo99s
  resources :foo98s
  resources :foo97s
  resources :foo96s
  resources :foo95s
  resources :foo94s
  resources :foo93s
  resources :foo92s
  resources :foo91s
  resources :foo90s
  resources :foo89s
  resources :foo88s
  resources :foo87s
  resources :foo86s
  resources :foo85s
  resources :foo84s
  resources :foo83s
  resources :foo82s
  resources :foo81s
  resources :foo80s
  resources :foo79s
  resources :foo78s
  resources :foo77s
  resources :foo76s
  resources :foo75s
  resources :foo74s
  resources :foo73s
  resources :foo72s
  resources :foo71s
  resources :foo70s
  resources :foo69s
  resources :foo68s
  resources :foo67s
  resources :foo66s
  resources :foo65s
  resources :foo64s
  resources :foo63s
  resources :foo62s
  resources :foo61s
  resources :foo60s
  resources :foo59s
  resources :foo58s
  resources :foo57s
  resources :foo56s
  resources :foo55s
  resources :foo54s
  resources :foo53s
  resources :foo52s
  resources :foo51s
  resources :foo50s
  resources :foo49s
  resources :foo48s
  resources :foo47s
  resources :foo46s
  resources :foo45s
  resources :foo44s
  resources :foo43s
  resources :foo42s
  resources :foo41s
  resources :foo40s
  resources :foo39s
  resources :foo38s
  resources :foo37s
  resources :foo36s
  resources :foo35s
  resources :foo34s
  resources :foo33s
  resources :foo32s
  resources :foo31s
  resources :foo30s
  resources :foo29s
  resources :foo28s
  resources :foo27s
  resources :foo26s
  resources :foo25s
  resources :foo24s
  resources :foo23s
  resources :foo22s
  resources :foo21s
  resources :foo20s
  resources :foo19s
  resources :foo18s
  resources :foo17s
  resources :foo16s
  resources :foo15s
  resources :foo14s
  resources :foo13s
  resources :foo12s
  resources :foo11s
  resources :foo10s
  resources :foo9s
  resources :foo8s
  resources :foo7s
  resources :foo6s
  resources :foo5s
  resources :foo4s
  resources :foo3s
  resources :foo2s
  resources :foo1s
  resources :foos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
