Rails.application.routes.draw do
  resources :baz100s
  resources :baz99s
  resources :baz96s
  resources :baz95s
  resources :baz97s
  resources :baz98s
  resources :baz94s
  resources :baz93s
  resources :baz91s
  resources :baz92s
  resources :baz88s
  resources :baz89s
  resources :baz90s
  resources :baz87s
  resources :baz85s
  resources :baz86s
  resources :baz83s
  resources :baz84s
  resources :baz82s
  resources :baz81s
  resources :baz78s
  resources :baz79s
  resources :baz80s
  resources :baz77s
  resources :baz74s
  resources :baz76s
  resources :baz75s
  resources :baz73s
  resources :baz72s
  resources :baz70s
  resources :baz71s
  resources :baz68s
  resources :baz69s
  resources :baz65s
  resources :baz66s
  resources :baz64s
  resources :baz67s
  resources :baz63s
  resources :baz62s
  resources :baz61s
  resources :baz60s
  resources :baz59s
  resources :baz58s
  resources :baz57s
  resources :baz56s
  resources :baz54s
  resources :baz53s
  resources :baz55s
  resources :baz52s
  resources :baz51s
  resources :baz49s
  resources :baz50s
  resources :baz47s
  resources :baz48s
  resources :baz46s
  resources :baz45s
  resources :baz44s
  resources :baz43s
  resources :baz41s
  resources :baz42s
  resources :baz38s
  resources :baz40s
  resources :baz39s
  resources :baz36s
  resources :baz37s
  resources :baz33s
  resources :baz35s
  resources :baz34s
  resources :baz31s
  resources :baz32s
  resources :baz30s
  resources :baz29s
  resources :baz25s
  resources :baz28s
  resources :baz26s
  resources :baz27s
  resources :baz24s
  resources :baz22s
  resources :baz23s
  resources :baz21s
  resources :baz20s
  resources :baz19s
  resources :baz17s
  resources :baz18s
  resources :baz16s
  resources :baz15s
  resources :baz13s
  resources :baz14s
  resources :baz12s
  resources :baz11s
  resources :baz9s
  resources :baz3s
  resources :baz8s
  resources :baz7s
  resources :baz6s
  resources :baz4s
  resources :baz5s
  resources :baz10s
  resources :baz1s
  resources :baz2s
  resources :bar100s
  resources :bar99s
  resources :bar98s
  resources :bar97s
  resources :bar96s
  resources :bar95s
  resources :bar94s
  resources :bar93s
  resources :bar92s
  resources :bar91s
  resources :bar90s
  resources :bar89s
  resources :bar88s
  resources :bar87s
  resources :bar86s
  resources :bar85s
  resources :bar84s
  resources :bar83s
  resources :bar82s
  resources :bar81s
  resources :bar80s
  resources :bar79s
  resources :bar78s
  resources :bar77s
  resources :bar76s
  resources :bar75s
  resources :bar74s
  resources :bar73s
  resources :bar72s
  resources :bar71s
  resources :bar70s
  resources :bar69s
  resources :bar68s
  resources :bar67s
  resources :bar66s
  resources :bar65s
  resources :bar64s
  resources :bar63s
  resources :bar62s
  resources :bar61s
  resources :bar60s
  resources :bar59s
  resources :bar58s
  resources :bar57s
  resources :bar56s
  resources :bar55s
  resources :bar54s
  resources :bar53s
  resources :bar52s
  resources :bar51s
  resources :bar50s
  resources :bar49s
  resources :bar48s
  resources :bar47s
  resources :bar46s
  resources :bar45s
  resources :bar44s
  resources :bar43s
  resources :bar42s
  resources :bar41s
  resources :bar40s
  resources :bar39s
  resources :bar38s
  resources :bar37s
  resources :bar36s
  resources :bar35s
  resources :bar34s
  resources :bar33s
  resources :bar32s
  resources :bar31s
  resources :bar30s
  resources :bar29s
  resources :bar28s
  resources :bar27s
  resources :bar26s
  resources :bar25s
  resources :bar24s
  resources :bar23s
  resources :bar22s
  resources :bar21s
  resources :bar20s
  resources :bar19s
  resources :bar18s
  resources :bar17s
  resources :bar16s
  resources :bar15s
  resources :bar14s
  resources :bar13s
  resources :bar12s
  resources :bar11s
  resources :bar10s
  resources :bar9s
  resources :bar8s
  resources :bar7s
  resources :bar6s
  resources :bar5s
  resources :bar4s
  resources :bar3s
  resources :bar2s
  resources :bar1s
  resources :foo100s
  resources :foo99s
  resources :foo98s
  resources :foo97s
  resources :foo96s
  resources :foo95s
  resources :foo94s
  resources :foo93s
  resources :foo92s
  resources :foo91s
  resources :foo90s
  resources :foo89s
  resources :foo88s
  resources :foo87s
  resources :foo86s
  resources :foo85s
  resources :foo84s
  resources :foo83s
  resources :foo82s
  resources :foo81s
  resources :foo80s
  resources :foo79s
  resources :foo78s
  resources :foo77s
  resources :foo76s
  resources :foo75s
  resources :foo74s
  resources :foo73s
  resources :foo72s
  resources :foo71s
  resources :foo70s
  resources :foo69s
  resources :foo68s
  resources :foo67s
  resources :foo66s
  resources :foo65s
  resources :foo64s
  resources :foo63s
  resources :foo62s
  resources :foo61s
  resources :foo60s
  resources :foo59s
  resources :foo58s
  resources :foo57s
  resources :foo56s
  resources :foo55s
  resources :foo54s
  resources :foo53s
  resources :foo52s
  resources :foo51s
  resources :foo50s
  resources :foo49s
  resources :foo48s
  resources :foo47s
  resources :foo46s
  resources :foo45s
  resources :foo44s
  resources :foo43s
  resources :foo42s
  resources :foo41s
  resources :foo40s
  resources :foo39s
  resources :foo38s
  resources :foo37s
  resources :foo36s
  resources :foo35s
  resources :foo34s
  resources :foo33s
  resources :foo32s
  resources :foo31s
  resources :foo30s
  resources :foo29s
  resources :foo28s
  resources :foo27s
  resources :foo26s
  resources :foo25s
  resources :foo24s
  resources :foo23s
  resources :foo22s
  resources :foo21s
  resources :foo20s
  resources :foo19s
  resources :foo18s
  resources :foo17s
  resources :foo16s
  resources :foo15s
  resources :foo14s
  resources :foo13s
  resources :foo12s
  resources :foo11s
  resources :foo10s
  resources :foo9s
  resources :foo8s
  resources :foo7s
  resources :foo6s
  resources :foo5s
  resources :foo4s
  resources :foo3s
  resources :foo2s
  resources :foo1s
  resources :foos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
